README.org
modeline/hostname/COPYRIGHT
modeline/hostname/README.org
modeline/hostname/hostname.asd
modeline/hostname/hostname.lisp
modeline/hostname/package.lisp

This is my first module and my first pull request, so please let me know if I've done anything stupid.

A simple module to show the hostname in the mode-line

---

minor-mode/mpd/mpd.lisp

This is the sum of my changes in mpd.lisp across the entire period I've been using it, for significant periods as my main MPD client. The changes mostly amount to:
- A bunch of trivial new features e.g. single mode handling, hours in time display
- Various bug fixes; the original code wasn't particularly stable under edge cases, and it caused a lot of random crashes, or at least random exceptions thrown for no identifiable reason
- Several big new things, including a full rewrite of `mpd-playlist` to have a decent-looking output, a revamp of the `mpd-browse-*` commands to enable browsing more conveniently, the new `mpd-browse-database` command along the same lines
I'd been intending to submit it for quite a while, and only now gotten around to it, hence the single enormous patch.

A bunch of miscellaneous fixes and new features

---

minor-mode/mpd/mpd.lisp

Fixed a crash which caused connection to break in the default configuration if the MPD doesn't send xfade information, and added the ability to load playlists in the file tree from `mpd-browse-database`.

A few minor changes

---

util/swm-emacs/swm-emacs.lisp

This approach let use emacs in stumpwm more comfortable, suggest merge.
At the moment, the problem are:
1.  My approach require "cl-fad", but I don't how to deal with it.
2. The code did not polish  very well for it it beyond my common lisp ability.

New version swm-emacs

---

util/alert-me/README.org
util/alert-me/alert-me.asd
util/alert-me/alert-me.lisp
util/alert-me/package.lisp

Adds the alert-me stumpwm module.

---

media/amixer/amixer.lisp

this fixes the interaction with newer versions of amixer

Append % sign to volume control units

---

util/notify/README.org
util/notify/notify.asd
util/notify/notify.lisp
util/notify/package.lisp

Allows to show incoming org.freedesktop.Notification right in StumpWM.
Signed-off-by: Slava Barinov <rayslava@gmail.com>

Added notification server

---

util/notify/notify.lisp
util/notify/package.lisp

Fix notify

---

util/perwindowlayout/perwindowlayout.lisp

- simplified code
- added SPOT
- probably fixed a race condition

util: perwindowlayout: fixed spurious layout sticking/bouncing

---

util/pinentry/pinentry.asd
util/pinentry/pinentry.lisp
util/pinentry/stumpwm-pinentry

You know, the last line you add before committing, and really, it won't break anything? Yeah, that one.
`echo D $PID` was breaking pinentry.
The rest is general cleanup.

Fix pinentry.

---

util/searchengines/package.lisp
util/searchengines/searchengines.lisp

Minor clean-ups and revert commit https://github.com/stumpwm/stumpwm-contrib/commit/7cf59374677b706a15d8904b9ebdffd7e805f184

SearchEngines Contrib

---

util/swm-gaps/swm-gaps.lisp

Export *gaps-on* variable in swm-gaps module

---

util/pinentry/README.org
util/pinentry/pinentry.asd
util/pinentry/pinentry.lisp
util/pinentry/stumpwm-pinentry

I also added a roadmap for some stuff I want to do in the module. Given that I already have these improvements in there, might as well make everyone enjoy them though, so here goes.

pinentry: take advantage of multi-lines prompts

---

README.org
util/end-session/README.org
util/end-session/end-session.asd
util/end-session/end-session.lisp
util/end-session/package.lisp

See the README for this module, or [this other pull request](https://github.com/stumpwm/stumpwm/pull/444). Note that some function names have changed since that pull request.

Add end-session module

---

util/end-session/end-session.lisp

Add `suspend-computer` to `end-session` commands.

Add suspend command

---

util/notify/notify.lisp

Make *notification-received-hook* a hook

---

util/swm-emacs/swm-emacs.asd

This fix has been proposed by PuercoPop.  See the comment of at
https://github.com/stumpwm/stumpwm-contrib/issues/105 .

Fix dependencies in swm-emacs

---

media/amixer/amixer.lisp
media/amixer/package.lisp

I need default-device to be pulse, not "default"

Configurable default device

---

util/stumptray/README.org

- Add information about how correctly to use StumpTray.
- Add Dependencies
- Update Usage 
- and add a new fix to be fixed

Stumptray README: updating

---

README.org

Hi,
Stumpwm-contrib main README.org upper part, I think, need some minor improvement.

Main README.org - Improving text

---

util/desktop-entry/README.org

quicklisp typo

---

README.org
util/shell-command-history/README.org
util/shell-command-history/package.lisp
util/shell-command-history/shell-command-history.asd
util/shell-command-history/shell-command-history.lisp

Hello!
Thank you for this wonderful WM!
This is just a quick hack that i wrote with simple modification of command-history.
I found it useful, though! :)
Bye!
C.

- added module to make shell history persistent.

---

media/amixer/amixer.lisp

Added mute and unmute options to the available volume controls for convenience

added mute and unmute controls for amixer

---

util/command-history/command-history.lisp
util/command-history/package.lisp

Hi!
I think could be useful, when configuring,  export this symbol too.
Bye!
C.

- exported symbol *command-history-file*.

---

README.org
util/browse/README.org
util/browse/browse.asd
util/browse/browse.lisp
util/browse/package.lisp

Very simple package for opening the default browser. Only about 3 lines of interesting code.

Add browse package -- open default browser portably.

---

media/stump-radio/README
media/stump-radio/package.lisp
media/stump-radio/radio.lisp
media/stump-radio/stump-radio.asd

 a simple mplayer-based radio for the window manager StumpWM

---

media/stump-volume-control/README
media/stump-volume-control/package.lisp
media/stump-volume-control/stump-volume-control.asd
media/stump-volume-control/volume-control.lisp

see readme for details
Used and tested on two systems, one with PulseAudio and one with just ALSA.

 very simple volume control for the window manager StumpWM

---

util/swm-ssh/README.org
util/swm-ssh/package.lisp
util/swm-ssh/swm-ssh.asd
util/swm-ssh/swm-ssh.lisp

Simple package for parsing ssh config file and lets the user select a host to ssh to.
Comments/criticism welcome (especially on coding style), as it's my first try to build a module (or anything really) in common lisp/stumpwm.

Add swm-ssh module

---

util/swm-gaps/swm-gaps.lisp

Fixes #178, possibly fixes #75 as well

swm-gaps: fix crash and issues with small windows

---

README.org
modeline/bitcoin/README.org
modeline/bitcoin/bitcoin.asd
modeline/bitcoin/bitcoin.lisp
modeline/bitcoin/package.lisp

Just showing actual price on modeline. Thanks for review.

New module bitcoin for modeline

---

util/stump-backlight/README.org
util/stump-backlight/backlight.lisp
util/stump-backlight/package.lisp

As a follow-up from yesterday's PR :)

Make stump-backlight work correctly on multiple monitors.

---

util/notify/README.org
util/notify/notify.lisp

Moves dbus spec reference to the README file

Notify move dbus spec ref

---

modeline/bitcoin/README.org
modeline/bitcoin/bitcoin.asd
modeline/bitcoin/bitcoin.lisp
modeline/bitcoin/package.lisp

Let's celebrate the 2020 20k. Improved with three colors and a condition/restart.
Thanks

bitcoin: updated module

---

README.org
media/stumpwm-sndioctl/README.md
media/stumpwm-sndioctl/package.lisp
media/stumpwm-sndioctl/stumpwm-sndioctl.asd
media/stumpwm-sndioctl/stumpwm-sndioctl.lisp

Adds an interface to OpenBSD's sndioctl, for controlling volume with keys etc.

Add stumpwm-sndioctl

---

docs/PULL_REQUEST_TEMPLATE.md

I know its not much, but its enough to get the ball rolling, feel free to suggest other relevant information that should be included.

Add pull request template

---

modeline/cpu/cpu.lisp

- factor out formatting for the CPU usage output to allow for easier user config
- add bar-zone-colouring for CPU temperature
- with configurable levels, defaulting to reasonable values

updates to CPU mode-line formatters

---

util/wacom/README.org
util/wacom/package.lisp
util/wacom/wacom.asd
util/wacom/wacom.lisp

This is not ready for a merge, but it's a minimal working solution for my current use case and I wanted to make it available for anyone else who might find it useful and to get more eyes on the code.
I plan on cleaning it up and robustifying it in the next few weeks. If something comes up and this PR is stale in a month, feel free to delete.

Map Wacom tablets to StumpWM frames

---

util/surfraw/macros.lisp
util/surfraw/surfraw.asd
util/surfraw/surfraw.lisp

Without this, none of the surfraw commands are created.

Define surfraw commands at module-loading time.

---

util/surfraw/README.org

Updated Surfraw home page link in readme

Surfraw home page link updated

---

README.org
util/spatial-groups/README
util/spatial-groups/SpatialGroups.org
util/spatial-groups/package.lisp
util/spatial-groups/spatial-groups.asd
util/spatial-groups/spatial-groups.lisp

- [ X] Have you run `./update-readme.sh`?
I did it manually. The update script fails on FreeBSD.

[PR] Adding spatial groups to stumpwm-contrib

---

util/swm-clim-message/swm-clim-message.lisp

Change a typo using a non-existant symbol from stumpwm.

Use symbol from the correct package

---

README.org

Third party module that integrates some mullvad cli commands

Add stumpwm-mullvad third party module

---

util/binwarp/README.org

Fix small typo in binwarp

---

modeline/bitcoin/README.org
modeline/bitcoin/bitcoin.asd
modeline/bitcoin/bitcoin.lisp
modeline/bitcoin/package.lisp

Updated bitcoin module with gauge bar and asynchronous get-prices process, thanks to lparallel.

Bitcoin lparallel

---

util/swm-gaps/swm-gaps.lisp

Fixes swm-gaps crashing for negtive values for height (#205)

---

README.org

I moved the packages from gitlab -> codeberg

Update README.org with updated URLs

---

README.org
media/stumpwm-mixer/README.md
media/stumpwm-mixer/mixer.lisp
media/stumpwm-mixer/package.lisp
media/stumpwm-mixer/stumpwm-mixer.asd

Just a very simple module for the FreeBSD audio mixer ^^

Add module for FreeBSD's audio mixer

---

modeline/ticker/README.org
modeline/ticker/ticker.asd
modeline/ticker/ticker.lisp

Hello,
Debugged and refactored module from lparallel to bordeaux-threads. Should work smoother, especially in case of network cuts.
Regards and Thanks

modeline/ticker: refactored to use ordeaux-threads

---

modeline/battery-portable/battery-portable.lisp

This adds support for FreeBSD and NetBSD to the battery module. It uses read-time conditionals to determine how to parse the battery info because FreeBSD's APM is slightly different from OpenBSD's, so functionality should be unchanged if running OpenBSD, but I currently don't have an OpenBSD desktop to test this with. I also made the hasty assumption that NetBSD's APM output is the same as OpenBSD's since it was originally ported from NetBSD according to apm(8).

add battery support for freebsd, netbsd

---

util/windowtags/windowtags.lisp

- [ x] Have you run `./update-readme.sh`?

Fix raise-tag when there are no groups.

---

media/stumpwm-sndioctl/stumpwm-sndioctl.lisp

This new version was tested on two devices:
The first one:
input.level=0.694
input.mute=0
output.level=0.631
output.mute=0
server.device=0(azalia0)
And the second one
output.level=1.000
output.mute=0
server.device=1(uaudio0)
With and without input channel

sndioctl: support change input level

---

util/notify/notify.lisp

Escape special chars and some edge case fixes when showing the notification's details
