stumpwm/stumpwm-contrib

- util/sbclfix/sbclfix.lisp
I have not checked the exact version of SBCL when sbclfix broke, but the existing sbclfix seems rather old.
SBCL got :DIRECTORY arg to SB-EXT:RUN-PROGRAM in 1.1.8. - sbclfix must have preceeded that version.
My changes are quite straightforward, the semantics should be preserved.
If sbclfix is still required is another topic...
> Fixed sbclfix.lisp to compile on newer SBCLs.

- modeline/battery/README.org
- modeline/battery/battery.asd
- modeline/battery/battery.lisp
- modeline/battery/package.lisp
The idea is to handle errors more gracefully. in this case although it works on emacs (screenshoot attached), for the restart to be invoked in stumpwm we would have to modify `#'stumpwm-interal-loop` to recognize stumpwm conditions. I'm still trying to figure out how restart system works and how can `*query-io*` interact with the command system, which seems the natural fit for prompting the user for input. We could borrow more heavily from [CLIM command processing](http://www.lispworks.com/documentation/lw51/CLIM/html/climuser-193.htm#pgfId-407790) that StumpWM seems inspired on. 
This is depends on the PR https://github.com/stumpwm/stumpwm/pull/211 as it requires the stumpwm-error to be exported from the stumpwm package
I also cleaned up the style a little bit and addeda few suggestions …
> Add a restart in case the battery is not found.

- util/winner-mode/README.org
- util/winner-mode/dumper.lisp
- util/winner-mode/macros.lisp
- util/winner-mode/package.lisp
- util/winner-mode/variables.lisp
- util/winner-mode/winner-mode.asd
- util/winner-mode/winner-mode.lisp
winner-mode lets you have a similar workflow as in emacs, using its
winner-mode. Whenever possible, the layout is dumped to a file, and a
few commands let you cycle through the dumped layouts.
This module would love https://github.com/stumpwm/stumpwm/pull/230 to be merged, and the README.org could be updated to have the new hooks in it.
> Adds winner-mode module.

- util/winner-mode/winner-mode.lisp
In itself, it's not a big issue, but leftover files could be left in /tmp/ or w/e temporary folder is used.
> Clean up the dumps before leaving.

- util/qubes/README.org
- util/qubes/package.lisp
- util/qubes/qubes.asd
- util/qubes/qubes.lisp
This is a module for stumpwm for coloring the windows according to Qubes OS (https://www.qubes-os.org) properties. It also renames the window prefixing which domain they belong to. 
It overrides internal functions in :stumpwm, which I know is bad.
The really slim usecase for this module (it's really only applicable to someone running Qubes) makes it hard to argue for exporting those symbols from :stumpwm
Since this is my first module, any feedback is gladly appreciated. :)
> Adds qubes module to stumpwm.

- util/screenshot/screenshot.lisp
I installed stumpwm 0.9.9 and its contrib modules and test the screenshot module. I got an error indicating that stumpwm does not export the srceen-root function. Hacking a little bit I manage to get it working but surely the fix it is not the best one.
Thanks.
> Fix command screenshot in module screenshot

- modeline/battery/battery.lisp
Fallback for a problem battery that shows last full capacity as zero (and if hashes do not exist).
> Fallbacks for battery charge

- minor-mode/mpd/mpd.lisp
- minor-mode/notifications/notifications.lisp
- modeline/battery/battery.lisp
- modeline/cpu/cpu.lisp
- modeline/disk/disk.lisp
- modeline/maildir/maildir.lisp
- modeline/mem/mem.lisp
- modeline/net/net.lisp
Although not documented, it part of the public API of StumpWM's modeline. It helps discoverability.
> Use ADD-SCREEN-MODE-LINE-FORMATTER

- modeline/disk/disk.lisp
- modeline/disk/package.lisp
It is intended to be be modified by the user to customize the output of
the disk usage information so it should be exported.
> Export *DISK-MODELINE-FMT*

- util/stumptray/package.lisp
- util/stumptray/stumptray.lisp
This is a rather crude "solution" for #25. I'm not sure if we should merge something like this, but it's a workaround that does work.
With this, one can add `%T` to the mode line at the place the tray would be displayed. This is normally the right side, but that's configurable. If you don't use the default font, you also need to set `stumptray:*tray-placeholder-pixels-per-space*` to a number appropriate for the font used at the place of the placeholder.
Fixes #25
> Add stumptray mode line placeholder

- modeline/wifi/wifi.asd
- modeline/wifi/wifi.lisp
When disconnecting from a WiFi network, the "%I" on the modeline was
blinking from the last WiFi ESSID to NIL and back, until StumpWM got
restarted.
This change sets "no link" by default and also creates a surrounding
block lexical scope for the return-from to correctly work.
> Return from a explicit block that the return-from needs.

- media/amixer/amixer.lisp
This is done by simply showing an empty bar. This would solve #67.
> Show mute state in amixer notification

- media/amixer/amixer.lisp
amixer's output is (or can be) multiline. This breaks the regex, because
.* doesn't match newlines by default. Removing ^ should be a safe edit
because we aren't using anything from .* before the first [ anyway, with
or without the newlines. 
my system if it matters:
amixer version 1.1.4 (pulseaudio)
SBCL 1.3.16-2.1-suse
stumpwm "1.0.0-111-gb740b04 Compiled On Fri May 26 2017 12:56:04"
amixer's multiline output:
Simple mixer control 'Master',0
Capabilities: pvolume pswitch pswitch-joined
Playback channels: Front Left - Front Right
Limits: Playback 0 - 65536
Mono:
Front Left: Playback 15709 [24%] [on]
Front Right: Playback 15709 [24%] [on]
> Remove ^ from regex - .* doesn't include newlines

- README.org
- util/pinentry/README.org
- util/pinentry/pinentry.asd
- util/pinentry/pinentry.lisp
- util/pinentry/stumpwm-pinentry
This module lets you completely integrate GnuPG Agent with
StumpWM. After correctly configuring it, whenever gpg-agent will need
a passphrase for a GPG key (or an SSH key, if you have enabled SSH
support), a StumpWM prompt will ask for the password.
> Add a pinentry module.

- util/kbd-layouts/kbd-layouts.lisp
- util/kbd-layouts/package.lisp
Hi,
I've updated my module `xkb-layoutx` to allow automatic reload of xmodmap. It's helpful when you have some non-standard key mappings and want to preserve them over layout switches.
> Allow reloading xmodmap on each layout change

- README.org
- util/command-history/README.md
- util/command-history/README.org
- util/command-history/command-history.asd
- util/command-history/command-history.lisp
- util/command-history/package.lisp
I'd like to save the *input-history* on quitting StumpWM and reloading it again on start, so I can navigate to older commands.
> Save *input-history* on quitting StumpWM and reloading it again on start

- util/notify/README.org
- util/notify/notify.asd
- util/notify/notify.lisp
- util/notify/package.lisp
- export NOTIFY-SERVER-ON and NOTIFY-SERVER-OFF.
- NOTIFY-SERVER-ON does nothing if the server is already running.
- ASDF system definition, prefer strings to keywords and uniterned
symbols as per ASDF recommended best practices[0].
[0]: https://gitlab.common-lisp.net/asdf/asdf/blob/master/doc/best_practices.md#designating-a-system
> Misc changes to the NOTIFY contrib

- util/end-session/end-session.lisp
At the moment the `restart-computer` function doesn't actually restart the computer, because it uses the wrong command.
This pull request just changes the command used from `systemctl restart` to `systemctl reboot`.
> end-session (restart-computer): actually restart computer

- util/passwd/package.lisp
- util/passwd/passwd.asd
The package definition should USE the package STUMPWM not
STUMPWM-USER. STUMPWM-USER is designed to run exploratory code that uses
symbols from the STUMPWM package, the package itself exports no symbols.
This PR partially addresses #106. The code itself code remove the sbcl feature expressions and the documentation is still missing.
> Ensure PASSWD contrib loads

- modeline/wifi/README.org
- modeline/wifi/package.lisp
- modeline/wifi/wifi.lisp
The wifi module had no easy customisation options, so this adds some basic formatting ones internal to the module (implemented similarly to the *disk* module's formatting, so no format character clashes are introduced).
The default configuration is identical to before, so no changes in behaviour should be observable until the format string is changed by the user.
README has been updated to reflect the changes. I've tested it without any breakage.
> Additional customisation variables to wifi module

- media/amixer/amixer.asd
Hello!
Here's a small patch that fixes amixer's asd file, adding stumpwm as a dependency.
Thanks for StumpWM :-).
Pierre
> amixer: Depend on stumpwm.

- modeline/cpu/cpu.lisp
- modeline/disk/disk.lisp
- modeline/maildir/maildir.lisp
- modeline/mem/mem.lisp
- modeline/net/net.lisp
Modified cpu, net and mem modules to export a single modeline formatter.
Each module now comes with its own modeline format string and formatters.
Also added ip address formatter to net module.
Using the single formatter will probably break existing configurations but the default
format string for each module should match the previous behavior.
> Update to cpu, net and mem modeline modules

- modeline/maildir/README.org
- modeline/maildir/maildir.lisp
**Note:** I just started using StumpWM just over a week ago, so I might have messed up a few things. And haven't had that much experience with Common Lisp per se... but at least it works on my machine.
---
As the title says, changed the maildir module to support multiple maildirs -- at the cost of having to change the old interface. Mail changes are:
- changing the format string from `%M` to `%D` (Mail- **d** -ir, I know it's bad)
- substituting `*maildir-path*` for `*maildir-alist*`
- dropping a few older functions
I could imagine the possibility of adding backwards compatibility support, but there problem would be a very hack-y (in the bad sense) result that would a harder to hack around with (in the good sense).
I'm looking forward to criticism and improvments, but it will probably …
> Added support for multiple maildirs

- util/stumpish/stumpish
Currently, if you run `stumpish` with a command argument (i.e. not interactively) and the command does not produce any output, `stumpish` returns 1, even though it returns successfully.
$ stumpish vsplit
$ echo $?
1
This patch simply fixes this to be more inline with expected Unix behavior of returning 0 on success so `stumpish` will fit better when called from an external tool or script.
> Make stumpish be well-behaved and return 0 upon success

- util/pass/README.org
- util/pass/pass.lisp
When selecting a password to copy via `pass-copy` I often don't
remember the name under which I stored the password. Autocomplete in
`pass-copy` helps a bit, but I think a bit more visibility would be
nice.
This PR adds the function `pass-copy-menu`, which displays the
available password entries in a menu. The user can then select or
narrow down an entry via autocompletion.
@ralt Would you like to merge this?
> Add pass-copy-menu

- util/notify/notify.lisp
Hi, 
Gnome Notifier and Dunst separates notifications Summary from its Body.
Ive just add a newline to do as much.
> notify: add newline between summary and body. Dunst-like

- README.org
- update-readme.sh
This just cleans up a couple annoyances in the README-generation script:
1. Modules are sorted by name
2. When categorizing modules, be sure to match a directory (e.g. `/\/modeline\//` instead of `/modeline/`) just in case that keyword appears in a description.  The `minor-mode/notifications` module was being grouped in with `modeline` because it contains "modeline" in its description.
> Sort readme modules

- README.org
- util/golden-ratio/README.org
- util/golden-ratio/package.lisp
- util/golden-ratio/swm-golden-ratio.asd
- util/golden-ratio/swm-golden-ratio.lisp
This module resize your currently focused frame to be a bit bigger than the other frames.
This is my first time contributing common-lisp code, all feedback is welcome :smile:
> Add golden-ratio mode

- util/lookup/README.org
- util/lookup/lookup.asd
- util/lookup/lookup.lisp
- util/lookup/package.lisp
EDIT: Sorry, I should've provided some context for this PR. It scratches my personal itch of wanting to automate dictionary and search engine lookups. It works by plugging the user's query into one of pre-defined query URLs and running that in the browser through `xdg-open`.
> Add 'lookup' to 'util'

- README.org
- util/notify/README.org
I sure anyone using stumpwm would work this out pretty quickly, but I don't see any harm in
having the information ready there.
> Additional info for readme.

- modeline/disk/README.org
- modeline/disk/disk.asd
- modeline/disk/disk.lisp
- modeline/disk/package.lisp
Hi!
I tried to address #125, there are some issues with this approach:
- the size (available,  total etc.) shows the decimals  (this could be
probably better be fixed by the cl-diskspace library);
- to shows the mountpoint or the  device the old method (shell process
must be used);
- of course a new dependency is added.
> Disk usage use lisp lib

- util/pinentry/pinentry.lisp
Previously the arity was wrong, so this did not work at all. Now it does work.
> Bugfix: Add completions string (the empty string).

- util/swm-gaps/README.org
- util/swm-gaps/swm-gaps.lisp
A recent fix to an issue in stumpwm master (see [this commit](https://github.com/stumpwm/stumpwm/commit/072836f261db2dc2b61ec91e4b43451e6a72d0ab)) was partially getting reverted by the function redefinition that happens in swm-gaps module. This commit updates swm-gaps to reflect those changes.
> Update maximize-window override in swm-gaps to reflect recent changes in master

- util/pinentry/pinentry.lisp
This single line breaks it, since `initial-input` is a keyword argument (not a `&optional`).
> Fix pinentry too many keyword arguments

- modeline/disk/disk.lisp
- trapped cl-mount-info' conditions
If,  for  some  reasons,  the  file  containing  mount  information
(default "/etc/mtab")  can not be  opened, capture the  condition and
prevent stumpwm to crash.
PS: sorry for the mess with commits :(
> Disk usage use lisp lib, trap condition

- util/gnu-pw-mgr/gnu-pw-mgr.lisp
https://github.com/stumpwm/stumpwm/commit/54999e83f78400e51dbf1554c0d815ea0335dc11 broke the `gnu-pw-mgr` module. This fixes it.
> Fix gnu-pw-mgr for stumpwm [54999e8]

- util/notify/notify.lisp
Fix bug with long notification lines or too many notification lines crashing stump. Also add color customization for the notifications.
> Bug fixes and customizations

- util/globalwindows/globalwindows.lisp
Hello!
with the current stumpwm in master using globalwindow you get a message like:
"That window is already in the group default"
This quick patch fix that.
Bye!
C.
> removed annoying message

- util/pass/pass.lisp
* Should do nothing when NIL (eg. abort <kbd>C-g</kbd> was passed) is returned from
completing-read.
* It does not make sense to copy a password that does not exist, so
require-match.
> Fix C-g "Abort" when entering data for pass, require matches for copy

- util/undocumented/package.lisp
This deports this symbol, which is the only one in the package.
> Deport list-undocumented (should be NIL) from :undocumented

- util/pinentry/stumpwm-pinentry
Sends an error message when netcat `nc` is not installed, rather than silently failing.
> Add warning to install netcat for pinentry

- modeline/battery-portable/README.org
- modeline/battery-portable/battery-portable.lisp
Remove the need for `*prefer-sysfs*` since it tries both and uses the same format.
Removes the need for the user to set that, so it is removed from the readme.
> Try sysfs and procfs before giving up battery mode line

- util/notify/notify.lisp
SBCL complains because ```take``` is not an exported symbol of the stumpwm package.
> Fix notify plugin compilation

- util/swm-gaps/swm-gaps.lisp
I think that by default, SWM-GAPS shouldn't apply gaps to fullscreen windows.
If this shouldn't be, maybe I should add a `*apply-gaps-fullscreen-windows*` or something of the like to toggle this behavior.
> Change default gaps behavior, no gaps for fullscreen windows.

- util/pass/pass.asd
- util/pass/pass.lisp
pass has partial support for the XDG Base Directory specification. The most
common value for `$PASSWORD_STORE_DIR` is either unset or
`$XDG_DATA_DIR/password-store`
See man pass for details of this variable
> Add $PASSWORD_STORE_DIR support to pass for XDG

- modeline/battery-portable/battery-portable.lisp
No longer displays a mode line like this:
0:00+ 87%
On machines that always show 0:00 due to lack of support. Since it isn't helpful
for a running computer to show 0 time left on the battery, it is better to
remove this.
The new display is minimally changed for such machines:
\+ 87%
> Do not display 0:00 time

- minor-mode/mpd/mpd.lisp
As of commit 4c207ec1ad12ed6208c7e98ef4ed40db04efe4ba, functions menu-state-selected and menu-state-table are deprecated.
This commit reintroduces the capability to open the playlist menu.
> mpd: replace deprecated functions

- util/notify/notify.lisp
Chrome/chromium queries for certain capabilities at startup, which
must be provided by the notification server.
> Adds support for chrome and chromium notifications

- media/stump-volume-control/README
- media/stump-volume-control/volume-control.lisp
This is the behavior I have proposed for the amixer module in #194
> Unify amixer device options for stump volume control

- util/swm-gaps/swm-gaps.lisp
Very minor addition to export commands to turn gaps on and off explicitly. Not essential, but useful for starting applications or states that need gaps to be off.
> swm-gaps toggle-gaps-off and toggle-gaps-on

- media/amixer/amixer.lisp
Some want to use device numbers with `-c` others want device names with `-D` this PR unifies both options.
see discussion https://github.com/stumpwm/stumpwm-contrib/pull/187
I don't know where to put tests, I tested with:
```
(list (let ((*default-device* "default"))
(list (string= (translate-device-to-option nil) "-D default ")
(string= (translate-device-to-option 1) "-D hw:1 ")
(string= (translate-device-to-option "my-device") "-D my-device ")))
(let ((*default-device* 0))
(list (string= (translate-device-to-option nil) "-D hw:0 ")
(string= (translate-device-to-option 1) "-D hw:1 ")
(string= (translate-device-to-option "my-device") "-D my-device ")))
(let ((*default-device* nil))
(list (string= (translate-device-to-option nil) "")
(string= (translate-device-to-option 1) "-D hw:1 ") …
```
> unifiy -c and -D options for amixer

- util/beckon/README.org
- util/beckon/beckon.asd
- util/beckon/beckon.lisp
- util/beckon/package.lisp
Minimal contrib to beckon the mouse to the middle of current-window.
This is useful in conjunction with banish, or for multi monitor setups when you suddenly need the mouse (for those stubborn applications that still insist clickable interfaces).
I named it "beckon" with the intention of being able to bind `C-t b` to banish and `C-t B` to beckon (or vice versa).
Comments on the code or suggestions very welcome.
> New module "beckon" to fetch the mouse to the current window

- util/kbd-layouts/README.org
- util/kbd-layouts/kbd-layouts.lisp
reason:
I configure caps lock with xmodmap in a personal fashion.
This PR allows to set the kbd-layouts:*caps-lock-behavior* to :leave-alone
which will mak kbd-layouts to not change the caps lock configuration at all
with setxkbmap, which just caused trouble in my case.
general remark:
I also do not see any reason why kbd-layout should try to mess with the setting by default.
> add option :leave-alone for *caps-lock-behavior* to not send any CapsLock option at all

- README.org
- util/binwarp/README.org
- util/binwarp/binwarp.asd
- util/binwarp/binwarp.lisp
- util/binwarp/package.lisp
This add a new interactive-keymap-based mouse control mode (in the sense of `iresize` mode and maybe even Emacs modes) -- Binwarp. It operates on restricted screen area and divides it in two on every action, making mouse movement into a recursive binary divide-and-conquer task.
Also, the `beacon` README entry was added when I ran `update-readme.sh`, so I included it in the PR as a separate commit.
This mode appeared when my laptop touchpad died and I felt a need in going mouse-less in domain of mouse control :) For now, this module is already covering all my needs and even has some configuration bits that I don't use, so I thought it can be useful for someone else.
If this is more suitable for `minor-mode` directory, I'll move it there.
I'll be glad if you could review it and point at …
> Add binwarp mouse control mode

- README.org
- util/stump-nm/README.org
- util/stump-nm/nm-api.lisp
- util/stump-nm/package.lisp
- util/stump-nm/stump-nm.asd
- util/stump-nm/stump-nm.lisp
This module allows you to manage your Wi-Fi networks and VPN
connections from within StumpWM itself. It is intentionally pretty
bare-bones in features, in that it allows you to enable/disable
connections, and no more. It is not a replacement for `nmtui` and/or
`nmcli`.
It offers 2 commands:
- `nm-list-wireless-networks`
- `nm-list-vpn-connections`
Each command offers a menu where you can select a WiFi or VPN
connection.
More information in the README.org.
> Add stump-nm, a StumpWM and NetworkManager integration module.

- README.org
- util/stump-backlight/README.org
- util/stump-backlight/backlight.lisp
- util/stump-backlight/package.lisp
- util/stump-backlight/stump-backlight.asd
This module allows you to manage the backlight natively with StumpWM.
More details in the README.org file.
This is doing something a bit controversial: it binds 2 keys by default. However, those 2 keys have a single purpose, and this module's only responsibility is to fulfil this purpose, so I'd say it's fair. Happy to remove those keybindings and edit the README.org if it's too controversial.
> Add the stump-backlight module.

- util/stump-lock/README.org
- util/stump-lock/lock.lisp
- util/stump-lock/package.lisp
- util/stump-lock/stump-lock.asd
This very much takes advantage of the fact that stumpwm's `read-one-line` is grabbing the whole screen.
Worth noting: this is a screenlocker, not screensaver. It locks the screen.
> Add the stump-lock module, a screenlocker.

- util/golden-ratio/swm-golden-ratio.lisp
Hi there.
I just noticed that an error happened whenever I switched focus with the golden-ratio-mode toggled on, and the resize action wasn't applied at all.
This patch removes all errors, and the behaviour is now as expected.
Sorry for not providing any further details, such as error logs, as I'm not yet acquainted with stumwm. I even tried connecting with SLIME to do that but the error was only displayed as a message by stumpwm.
> fix stack exhaustion error

- util/notify/notify.lisp
Some apps like Firefox seem to revert to showing built-in notifications when stumpwm/notify is used as a DBUS notifications handler. This commit fixes the issue
> Adds "Close Notification" dbus method, some apps (Firefox) need it

- minor-mode/mpd/mpd.lisp
If components inside a cuefile are in the playlist, mpd-get-label will crash (due to expecting a dot after the final slash which it doesn't find). This fixes that.
Also includes some whitespace fixes from a long time ago that never got merged.
> MPD: fix crash with cuefile playlists

- README.org
- modeline/hidden/README.org
- modeline/hidden/hidden.asd
- modeline/hidden/hidden.lisp
- modeline/hidden/package.lisp
This modeline formatter shows how many windows are hidden behind the current frame in tiling groups.
> Add hidden window count modeline formatter

- modeline/clim-mode-line/README.org
- modeline/clim-mode-line/clim-clx-patch.lisp
- modeline/clim-mode-line/clim-mode-line.asd
- modeline/clim-mode-line/clim-mode-line.lisp
- modeline/clim-mode-line/mode-line-formatters.lisp
- modeline/clim-mode-line/presentations.lisp
- modeline/clim-mode-line/stumpwm-patch.lisp
Because were patching McCLIM internals, we need to keep up to date
with McCLIM itself. sheet-direct-xmirror has been changed to
sheet-direct-mirror, and we need to reflect that change in order to
use McCLIM. There is a PR open with McCLIM to implement this, but until they merge that (or inform of a different preferred way of making a window to dock type) this method needs to be tracked and kept up to date with McCLIM. 
additionally, majorly reworked how groups/windows are presented, such that now we can present groups/windows to a stream instead of using `with-output-as-presentation`. this new way is cleaner and more in line with how clim is designed to be used. Also updated readme with a clearer explanation of what needs to be done.
> update for change in McCLIM internals

- util/screenshot/screenshot.lisp
Below is a demo screenshot that I took while creating this PR. 
I'm a bit new to X11, CommonLisp, and StumpWM, so any feedback on the code is appreciated. For example, I'm not sure if I need to be "unwind-protect -> destroying windows", or if there's a generally cleaner way to achieve this functionality. It works as-is for my use-case. 
[
](url)
Referenced https://askubuntu.com/questions/487725/how-can-i-draw-selection-rectangle-on-screen-for-my-script for the code to get the selection rectangle redrawn as the mouse is moved.
> Add area-selection screenshot functionality

- README.org
- util/pomodoro/README.org
- util/pomodoro/package.lisp
- util/pomodoro/swm-pomodoro.asd
- util/pomodoro/swm-pomodoro.lisp
Reworked my simplistic pomodoro tracker, that I've been using for quite a while, into a contrib util. 
Optionally shows tracker status in the notifications area of stump-tray when `notifications` module is on.
> Pomodoro tracker with stumptray notifications

- util/stump-backlight/backlight.lisp
From https://github.com/stumpwm/stumpwm-contrib/issues/228
Backlight module was broken With CLX stemming from this commit
https://github.com/sharplispers/clx/commit/8e071554a5531988d21f088953de7b741c2b2980
```
Although this commit introduces two backwards-incompatible changes, they
should (hopefully) not be too inconvenient because this extension is as
yet unfinished and thus unsuitable for general use. The first, and more
important, change is the replacement of optional arguments with keyword
arguments in all request functions having optional arguments, which
affects only those callers who were supplying any optional arguments.
```
Calling backlight-increase or backlight-decrease would
result in error: "Error in Command 'backlight-increase': odd number of
&KEY arguments"
- [N/A] Have you …
> Fix backlight to work with new CLX api (Issue: #228)

- modeline/cpu/cpu.lisp
Use thermal zone with type `x86_pkg_temp` to fetch the cpu temperature.
> get correct thermal zone for cpu temp

- modeline/cpu/cpu.lisp
- modeline/cpu/package.lisp
Default behavior still just shows the frequency of cpu 0, modify `cpu:*cpu-modeline-fmt*` to enable the range
> Allow the cpu plugin to show a range of frequencies

- README.org
Add dmenu stumpwm integration as a thir party module.
It's base on [stumpwm-dmenu-wrapper](https://github.com/horellana/stumpwm-dmenu-wrapper) but with multiple screen/group support and .asd integration.
> Add stumpwm-dmenu third party module

- util/binwarp/binwarp.lisp
Pretty straight forward fix to hitting `j` in binwarp-mode caused the error `Command 'binwarp-down' not found`. This was due to the command `binwarp down` was misspelled as `binwarp-down`
> Removed non existent command binwarp-down in binwarp.lisp

- util/clipboard-history/clipboard-history.lisp
This PR fixes an exception which is thrown when viewing a menu of clipboard entries which contain caret (`^`) characters. This collides with the embedded color string sequence support in StumpWM. The fix is to escape such caret characters using `stumpwm::escape-caret`
> Escape any caret chars in clipboard entry display strings

- update-readme.sh
Update the `update-readme.sh` script so that the link in the top-level readme points to `README.md` ifone is present. Otherwise defaults to `README.org`
> update-readme.sh: Link to markdown file if one is present

- README.org
- util/swm-clim-message/README.org
- util/swm-clim-message/package.lisp
- util/swm-clim-message/reimplementations.lisp
- util/swm-clim-message/swm-clim-message.asd
- util/swm-clim-message/swm-clim-message.lisp
This implements a CLIM based message system, allowing for mouse based
interaction with message windows spawned via `swm-clim-message:clim-message`.
This module creates a CLIM frame and uses it to display messages and menus. 
Currently unsupported is entering text. This places the message/menu in the 
same place as the stumpwm message window. Both keyboard and mouse can be used 
to select an entry. The **bolded** item will be selected when `RET` is pressed
or the item chosen by mouse click will be selected. 
For an in depth description of this module please see the readme.
> Add CLIM based messaging module

- util/alert-me/alert-me.asd
- util/alert-me/alert-me.lisp
- util/pomodoro/package.lisp
- util/pomodoro/swm-pomodoro.asd
Fixed bug in `alert-me`. Tweaked `alert-me` and `pomodoro`, they compile ok with ASDF.
> Fixed alert-me and pomodoro clocks for asdf

- util/swm-ssh/swm-ssh.lisp
The SSH config file's keywords are case-insensitive, so I changed the swm-ssh module's regex accordingly since it wasn't working with my config.
> case-insensitive swm-ssh config parsing

- media/stumpwm-sndioctl/stumpwm-sndioctl.asd
Tiny quoting typo in the sndioctl module that was causing issues with loading it.
> fix sndioctl typo that breaks loading

- util/productivity/README.org
I don't know much about Common Lisp but without this, `productivity` mode wouldn't pick up the variable that was set in my init file, I found this StackOverflow post that says that two colons should be put before an unexported variable: https://stackoverflow.com/questions/8567155/why-colons-precede-variables-in-common-lisp
And my problem was solved.
> Use the correct way to set the variable in README for the productivity module

- minor-mode/mpd/mpd.lisp
This makes the mpd-volume-up and mpd-volume-down commands alert the new volume on run. It also fixes a bug with connection management that can lead to dangling timers.
> Tweaks to MPD module

- util/end-session/README.org
- util/end-session/end-session.lisp
honestly not sure why systemctl was used to begin with, loginctl has slightly better compatibility since it also works with elogind
a very petty change, but since its literally a matter of 3 words with no drawbacks, i just don't see a reason not to at least try
> miniscule compatibility improvement to end-session

- util/urgentwindows/urgentwindows.lisp
**Context**
- Using master branch (`e530d43131e26c3bb705e446ec829bf65ad97496`).
**Issue**
When trying to call `raise-urgent` after an urgent notification, this error occurs:
```
*Error In Command 'raise-urgent': 
The value #<TILE-GROUP 1:www> is not of type
(OR STRING SYMBOL CHARACTER)
when binding SB-IMPL::STRING2
```
**Fix**
Pass the _group-name_ instead of _tile-group_ to `gselect`.
> fix(urgentwindows): The value #<TILE-GROUP xxx> is not of type

- modeline/battery-portable/battery-portable.lisp
On my laptop, acpi shows:
$ acpi
Battery 0: Not charging, 99%
Within the battery-portable module, (sysfs-field path "status") reports this as "Not charging".
In order to let the battery not be in an :unknown state, this change allows "Not charging" to be recognized as :charging in addition to "Full".
> Recognize battery state "Not charging" as :charged

- modeline/wifi/package.lisp
- modeline/wifi/wifi.lisp
- util/end-session/README.org
- util/end-session/end-session.lisp
- util/end-session/package.lisp
Allow users to configure how the signal quality is formatted instead of having it hardcoded.
Allow users to configure whether to use `systemctl` or `loginctl`, this is in response to the changes in pull request #259.
- [ x] Have you run `./update-readme.sh`?
> Allow more user configuration in the wifi and end-session modules

- modeline/cpu/README.org
The current README.org is confusing. When you read it, it seems like you have to add "%c" "%t" to *screen-mode-line-format*, which is incorrect. Actually, you should add "%C". Therefore, I changed the README.org a bit to make it clearer.
> modeline/cpu: update README.org

- util/swm-ssh/README.org
- util/swm-ssh/swm-ssh.lisp
Unfortently, config may contains wildcard based domains which makes it usless for this module, but from another hand the known_hosts is good source for known connections.
Thus, tramp uses the same idea.
> Use known_hosts as source at swm-ssh

- util/pinentry/pinentry.lisp
- util/pinentry/stumpwm-pinentry
Instead using nc and dedicated thread which lock current screen, use stumpish to run the function.
It is a bit slower, but way stable than old way.
It includes https://github.com/stumpwm/stumpwm-contrib/pull/287 and https://github.com/stumpwm/stumpwm-contrib/pull/288
> Move pinentry to stumpish

- util/pinentry/pinentry.lisp
Here two changes which dramatically increase stability.
Before this and https://github.com/stumpwm/stumpwm-contrib/pull/287 my stumpwm crashes on entering PIN quite often.
After this two PRs I can't crash it anymore.
> Pinentry: increase stability

- media/stumpwm-sndioctl/package.lisp
- media/stumpwm-sndioctl/stumpwm-sndioctl.lisp
When another user stream something like mpd, sndioctl can't increase or decrease volume when is runned from non root user.
Here I've added a simple way to enforce doas which is an equiualent for sudo for OpenBSD -- the only platform where sndioctl exists.
> Allow to use doas to run sndioctl

- util/stumpish/stumpish
`stumpish` depends on bash by using `read -p` for example, so it hasn't got any chance to ran well on anything else.
And `/bin/sh` not always bash, it might be something very limited.
> Use bash at stumpish

- modeline/stumptray/stumptray.lisp
Currently broken with the two-color specification, e.g. `("#DDDDDD" "white")` recently added to stumpwm; this patch should restore the original behaviour, which would have been to use the "bright" version of the colors specified.
> Make stumptray work with explicit background/foreground colors

- util/stumpish/stumpish
This MR is to ensure that stumpish only runs commands with an exclusive file lock and verifies that there is actually a StumpWM process running. There are a lot of issues with stumpish and it requires an overhaul but it's a beginning.
> Exclusive file lock during cmd execution and some bugs.

- util/stumpish/stumpish
This fixes regression which was introduced by https://github.com/stumpwm/stumpwm-contrib/pull/296
> Make stumpish work on OpenBSD again

- util/swm-ssh/swm-ssh.lisp
`-T` seems universal way to setup title which works on both xterm and urxvt
> Use ssh hostname in window title, instead just ssh

- README.org
- util/xinput-toggle/README.org
- util/xinput-toggle/package.lisp
- util/xinput-toggle/xinput-toggle.asd
- util/xinput-toggle/xinput-toggle.lisp
`xinput-toggle` can be used to enable, disable or toggle devices such as the mouse, touchpad, etc...
The motivation to write this module was to disable my laptop touchpad which accidentally gets engaged while typing. There was no straightforward way to do so without a script.
Hopefully this module makes it convenient to toggle the touchpad and other devices. It uses [xinput](https://linux.die.net/man/1/xinput) which is part of the [X.org](https://www.x.org/wiki/) suite of tools.
Comments and suggestions for improvement are welcome.
> Add module xinput-toggle

- modeline/stumptray/package.lisp
- modeline/stumptray/stumptray.lisp
I found that stumptray drew images too close to each other, so I fixed that by adding an exported parameter *tray-icon-spacing* to set the icon spacing. I also added some logic behind the default y positioning so that it's not drawn on the little rectangle that stumpwm draws around the mode-line. It's now drawn in the middle of the mode-line.
Before:
After:
The spacing can be modified by doing
```lisp
(setf stumptray:*tray-icon-spacing* 1)
```
In init.lisp.
> stumptray: Adjust icon vertical and horizontal spacing

- update-readme.sh
Before this fix, the `./update-readme.sh` could not be executed in the FreeBSD. The `bash` shell doesn't installed in the `/bin/bash` because it is not included in the "base system" in the FreeBSD.
Since it is not included — it is installed in the `/usr/local/bin/bash`, so the mentioned script could not be launched. Instead, the error about not found command will be issued:
```
drag0n@freebsd:~/git_repos/stumpwm-contrib $ ./update-readme.sh
-sh: ./update-readme.sh: not found
```
To make the script not the Linux-specific, the shebang should looks like this:
```shell
#!/usr/bin/env bash
```
Not like this:
```shell
#!/bin/bash
```
The `env` will find the bash interpreter in the user's `PATH` environment variable.
*Note:* this fix will not work in some obscure systems without `/usr/bin/env`. …
> Fix Linux-specific line in the update-readme.sh script
